# module1 Makefile
DIR_CUR = $(shell pwd)
DIR_SRCS = $(DIR_CUR)/src
DIR_INCS += $(DIR_CUR)/inc
DIR_OBJS = objs
DIR_DEPS = deps
DIR_LIBS = ../../build/libs/static
# library type an name
LIB_TYPE = static
LIBS = libmodule1.a
# LIB_TYPE = dynamic
# LIBS = libmodule1.so

include ../../rules.mk