TOPDIR = ..
# Current directory  Makefile
CURDIR = $(shell pwd)

# executable file name
EXES = justest

# head file directories
DIR_INCS = module1/inc\
           module2/inc\
           module3/inc

# objs and dependant file directories
DIR_OBJS = objs
DIR_DEPS = deps

# static libraries
LINK_LIBS = module1 module2 module3

# library file directories
DIR_LIBS = $(TOPDIR)/build/libs/static\
           $(TOPDIR)/build/libs/dynamic

# include common rule makefile
include ../rules.mk